# Generated by Django 2.2.7 on 2019-11-13 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2019, 11, 13, 10, 53, 40, 373665)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='12345678', max_length=30),
            preserve_default=False,
        ),
    ]
