# Generated by Django 2.2.7 on 2019-11-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191113_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birthday',
            new_name='birth_date',
        ),
    ]
