# Generated by Django 2.2.7 on 2019-11-14 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permission_level',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
