# Generated by Django 2.2.7 on 2019-11-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customuser_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='permission_level',
        ),
    ]
