# Generated by Django 2.2.7 on 2019-11-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customuser_permission_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permission_level',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
