# Generated by Django 2.2.7 on 2019-11-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_permission_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='permission_level',
        ),
    ]
