# Generated by Django 2.2.7 on 2019-11-20 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_customuser_permission_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='users',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='members',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
