# Generated by Django 2.2.7 on 2019-11-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventplan', '0012_auto_20191120_0744'),
        ('users', '0014_auto_20191120_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='shifts',
            field=models.ManyToManyField(blank=True, to='eventplan.Shift'),
        ),
    ]
