# Generated by Django 2.2.7 on 2019-11-13 20:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventplan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), blank=True, default=list, size=None),
        ),
    ]
