# Generated by Django 2.2.7 on 2019-11-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventplan', '0002_auto_20191113_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveSmallIntegerField(blank=True, default=3),
        ),
    ]
