# Generated by Django 2.2.7 on 2019-11-17 13:20

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventplan', '0008_auto_20191117_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='shifts',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveSmallIntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
