# Generated by Django 2.2.7 on 2019-11-18 05:18

from django.db import migrations, models
import django.utils.timezone
import eventplan.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventplan', '0010_auto_20191117_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=eventplan.models.event_end_offset),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
