# Generated by Django 2.2.7 on 2019-11-20 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventplan', '0011_auto_20191118_0618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['start']},
        ),
    ]
